// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/fav_quotes.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 107003377523531851),
      name: 'FavoriteQuotes',
      lastPropertyId: const IdUid(8, 1758297961225343280),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5265897239754987656),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(4, 4383758419637284890),
            name: 'quote',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1758297961225343280),
            name: 'isLiked',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 107003377523531851),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6760576888551701571,
        7233159079660918614,
        5705115646534446827,
        1733775147159140297,
        5083656934223189307
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    FavoriteQuotes: EntityDefinition<FavoriteQuotes>(
        model: _entities[0],
        toOneRelations: (FavoriteQuotes object) => [],
        toManyRelations: (FavoriteQuotes object) => {},
        getId: (FavoriteQuotes object) => object.id,
        setId: (FavoriteQuotes object, int id) {
          object.id = id;
        },
        objectToFB: (FavoriteQuotes object, fb.Builder fbb) {
          final quoteOffset = fbb.writeString(object.quote);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(3, quoteOffset);
          fbb.addBool(7, object.isLiked);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = FavoriteQuotes(
              quote: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              isLiked: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 18, false))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [FavoriteQuotes] entity fields to define ObjectBox queries.
class FavoriteQuotes_ {
  /// see [FavoriteQuotes.id]
  static final id =
      QueryIntegerProperty<FavoriteQuotes>(_entities[0].properties[0]);

  /// see [FavoriteQuotes.quote]
  static final quote =
      QueryStringProperty<FavoriteQuotes>(_entities[0].properties[1]);

  /// see [FavoriteQuotes.isLiked]
  static final isLiked =
      QueryBooleanProperty<FavoriteQuotes>(_entities[0].properties[2]);
}
